version: "3.4"

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    ports:
        - "15672:15672"
        - "5672:5672"
    networks:
      mafia_network:

  server:
    build:
      context: ./
      dockerfile: server/server.dockerfile
    container_name: prac3_server
    environment:
      MAFIA_SERVER_ADDRESS: 'server:50051'
    ports:
      - 50051:50051
    networks:
      mafia_network:
    depends_on:
      - rabbitmq

  client1:
    build:
      context: ./
      dockerfile: client/client.dockerfile
    container_name: prac3_client1
    environment:
      MAFIA_USERNAME: 'Bob'
      MAFIA_SERVER_ADDRESS: 'server:50051'
    networks:
      mafia_network:
    depends_on:
      - server

  client2:
    build:
      context: ./
      dockerfile: client/client.dockerfile
    container_name: prac3_client2
    environment:
      MAFIA_USERNAME: 'Alice'
      MAFIA_SERVER_ADDRESS: 'server:50051'
    networks:
      mafia_network:
    depends_on:
      - server

  client3:
    build:
      context: ./
      dockerfile: client/client.dockerfile
    container_name: prac3_client3
    environment:
      MAFIA_USERNAME: 'John'
      MAFIA_SERVER_ADDRESS: 'server:50051'
    networks:
      mafia_network:
    depends_on:
      - server

  client4:
    build:
      context: ./
      dockerfile: client/client.dockerfile
    container_name: prac3_client4
    environment:
      MAFIA_USERNAME: 'Nick'
      MAFIA_SERVER_ADDRESS: 'server:50051'
    networks:
      mafia_network:
    depends_on:
      - server

networks:
  mafia_network:
    driver: bridge
