version: "3.4"

services:
  server:
    build:
      context: ./
      dockerfile: server/server.dockerfile
    container_name: prac2_server
    environment:
      MAFIA_SERVER_ADDRESS: 'server:50051'
    ports:
      - 50051:50051
    networks:
      mafia_network:

  client1:
    build:
      context: ./
      dockerfile: client/client.dockerfile
    container_name: prac2_client1
    environment:
      MAFIA_USERNAME: 'Bob'
      MAFIA_SERVER_ADDRESS: 'server:50051'
    networks:
      mafia_network:
    depends_on:
      - server

  client2:
    build:
      context: ./
      dockerfile: client/client.dockerfile
    container_name: prac2_client2
    environment:
      MAFIA_USERNAME: 'Alice'
      MAFIA_SERVER_ADDRESS: 'server:50051'
    networks:
      mafia_network:
    depends_on:
      - server

  client3:
    build:
      context: ./
      dockerfile: client/client.dockerfile
    container_name: prac2_client3
    environment:
      MAFIA_USERNAME: 'John'
      MAFIA_SERVER_ADDRESS: 'server:50051'
    networks:
      mafia_network:
    depends_on:
      - server

  client4:
    build:
      context: ./
      dockerfile: client/client.dockerfile
    container_name: prac2_client4
    environment:
      MAFIA_USERNAME: 'Nick'
      MAFIA_SERVER_ADDRESS: 'server:50051'
    networks:
      mafia_network:
    depends_on:
      - server

networks:
  mafia_network:
    driver: bridge
